/**
 * Automated Bug Reporter
 * Generates structured bug reports in the exact enterprise format.
 */

export function generateBugReport(data) {
  const {
    testingBuild = '',
    serverUrl = '',
    issueDetails = '',
    stepsToReproduce = '',
    expectedResult = '',
    actualResult = '',
    logEvidence = '',
    severity = 'High',
    priority = 'High',
    reporter = '',
    assignee = '',
    environment = '',
    module = '',
  } = data;

  const reportId = `BUG-${Date.now().toString(36).toUpperCase()}`;
  const timestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'medium',
  });

  const report = `
╔══════════════════════════════════════════════════════════════════╗
║              ELITE QA CO-PILOT — BUG REPORT                     ║
║  Report ID: ${reportId.padEnd(50)}║
║  Generated: ${timestamp.padEnd(50)}║
╚══════════════════════════════════════════════════════════════════╝

━━━ BUILD INFORMATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Testing Build:      ${testingBuild}
Testing Server URL: ${serverUrl}
Environment:        ${environment}
Module/Feature:     ${module}

━━━ ISSUE CLASSIFICATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Severity:           ${severity}
Priority:           ${priority}
Reporter:           ${reporter}
Assigned To:        ${assignee}

━━━ ISSUE DETAILS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${issueDetails}

━━━ STEPS TO REPRODUCE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${stepsToReproduce}

━━━ EXPECTED RESULT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${expectedResult}

━━━ ACTUAL RESULT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${actualResult}

━━━ LOG EVIDENCE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${logEvidence || '[ No log evidence attached — attach via Neural Log Analyzer ]'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by: Elite QA Co-Pilot v1.0.0
`.trim();

  return { report, reportId, timestamp };
}

export function prefillFromBug(bug) {
  if (!bug) return {};
  return {
    issueDetails: `[${bug.level}] ${bug.title}`,
    stepsToReproduce: `1. Review log evidence at line ${bug.startLine}.\n2. Reproduce the conditions that triggered: "${bug.title}".\n3. Observe the ${bug.level} error.`,
    expectedResult: 'System should handle this condition gracefully without errors.',
    actualResult: `System threw a ${bug.level}: ${bug.title}`,
    logEvidence: bug.snippet.join('\n'),
  };
}

export const SEVERITY_OPTIONS = ['Critical', 'High', 'Medium', 'Low'];
export const PRIORITY_OPTIONS = ['P1 - Blocker', 'P2 - High', 'P3 - Medium', 'P4 - Low'];
export const ENV_OPTIONS = ['Production', 'Staging', 'QA', 'Development', 'UAT'];
